services:
  agent:
    image: agent-app
    build:
      context: .
      target: agent
    environment:
      - COMPUTING_POWER=10

  orchestrator:
    image: orchestrator-app
    build:
      context: .
      target: orchestrator
    ports:
      - "8080:8080"
    environment:
      - TIME_ADDITION_MS=100
      - TIME_SUBTRACTION_MS=100
      - TIME_MULTIPLICATIONS_MS=100
      - TIME_DIVISIONS_MS=100
      - COMPUTING_POWER=10